apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  selector:
    matchLabels:
      app: docker-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
        image: svsrvardhan/docker-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        
---

apiVersion: v1
kind: Service 
metadata:
  name: docker-demo
spec:
  selector:
    app: docker-demo    
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP 
  type: NodePort     
